[package]
name = "perlin"
version = "0.0.0"
authors = ["Jakob Demler <jdemler@curry-software.com>"]

[[example]]
name = "text-retrieval"
path = "examples/text-retrieval/main.rs"

[dev-dependencies]
rand = "0.3"
lazy_static = "0.2.1"
walkdir = "0.1"
time = "0.1.35"